[2024-04-16T01:19:27.097+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:27.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:19:27.099+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:19:27.099+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:28.027+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:19:28.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:28.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.943 seconds
[2024-04-16T01:19:58.775+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:58.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:19:58.779+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:19:58.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:59.108+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:19:59.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:19:59.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.348 seconds
[2024-04-16T01:20:29.517+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:20:29.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:20:29.520+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:20:29.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:20:29.936+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:20:29.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:20:29.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.432 seconds
[2024-04-16T01:21:00.277+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:00.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:21:00.280+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:21:00.279+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:00.679+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:21:00.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:00.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.419 seconds
[2024-04-16T01:21:31.516+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:31.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:21:31.521+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:21:31.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:31.974+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:21:31.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:21:31.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.483 seconds
[2024-04-16T01:22:02.244+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:02.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:22:02.246+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:22:02.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:02.605+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:22:02.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:02.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.376 seconds
[2024-04-16T01:22:33.533+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:33.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:22:33.536+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:22:33.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:33.854+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:22:33.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:22:33.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.336 seconds
[2024-04-16T01:23:03.940+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:03.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:23:03.943+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:23:03.943+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:04.351+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:23:04.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:04.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.424 seconds
[2024-04-16T01:23:34.612+0000] {processor.py:161} INFO - Started process (PID=539) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:34.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:23:34.615+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:23:34.615+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:34.934+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:23:34.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:23:34.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.334 seconds
[2024-04-16T01:24:05.803+0000] {processor.py:161} INFO - Started process (PID=600) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:05.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:24:05.820+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:24:05.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:06.201+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:24:06.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:06.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.414 seconds
[2024-04-16T01:24:36.652+0000] {processor.py:161} INFO - Started process (PID=662) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:36.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:24:36.731+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:24:36.730+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:37.059+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:24:37.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:24:37.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.421 seconds
[2024-04-16T01:25:07.331+0000] {processor.py:161} INFO - Started process (PID=725) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:07.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:25:07.344+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:25:07.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:07.952+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:25:07.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:07.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.649 seconds
[2024-04-16T01:25:38.507+0000] {processor.py:161} INFO - Started process (PID=787) to work on /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:38.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/db_connection.py for tasks to queue
[2024-04-16T01:25:38.510+0000] {logging_mixin.py:188} INFO - [2024-04-16T01:25:38.510+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:38.868+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-04-16T01:25:38.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection.py
[2024-04-16T01:25:38.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/db_connection.py took 0.374 seconds
